[package]
org = "wso2"
name = "ips.generation.demo"
version = "1.0.0"
distribution = "2201.12.3"
keywords = ["Healthcare", "FHIR", "Patient", "r4", "health.fhir.r4.uscore501"]

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4"
version = "6.0.1"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "health.fhir.r4.ips"
version = "2.0.1"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "health.fhirr4"
version = "2.0.4"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "health.clients.fhir"
version = "3.0.0"
repository = "local"
